// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmmczucvodxeetuplaur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbWN6dWN2b2R4ZWV0dXBsYXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDk1MzMsImV4cCI6MjA2OTg4NTUzM30.bz0wL5NzzRgSorGQ5ikm6DIpXeiM7djlP9OecatBagE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});